version: '3'
services:

  patika-db:
    image: postgres
    container_name: patika-postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: patika-user
      POSTGRES_PASSWORD: patika-password
      POSTGRES_DB: postgres
    networks:
      - patikaNetwork

  patika-redis:
    image: redis
    container_name: patika-redis
    ports:
      - '6379:6379'
    environment:
      ALLOW_EMPTY_PASSWORD: yes
    networks:
      - patikaNetwork


  patika-bootcamp-project:
    build: ./
    container_name: patika-bootcamp-project
    depends_on:
      - patika-db
      - patika-redis
    ports:
      - '8080:8080'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://patika-db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=patika-user
      - SPRING_DATASOURCE_PASSWORD=patika-password
    networks:
      - patikaNetwork

networks:
  patikaNetwork:
    driver: "bridge"